version: "3.7"

services:
  auth:
    build:
      context: ./server
      dockerfile: docker/auth/Dockerfile
    image: auth-image-prod
    container_name: auth-container-prod
    env_file: server/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    networks:
      - app-network
  io:
    build:
      context: ./server
      dockerfile: docker/io/Dockerfile
    image: io-image-prod
    container_name: io-container-prod
    env_file: server/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:8080"
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./
      dockerfile: Dockerfile.prd
    ports:
      - "3000:8080"
    image: client-image-prod
    container_name: client-container-prod
    # env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      NODE_ENV: production
    depends_on:
      - mongo
      - auth
      - io
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
